project_id = "pogo-raid-premium-backend"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "https://pogo-raid-premium.plbanos92.workers.dev"
additional_redirect_urls = ["https://pogo-raid-premium.plbanos92.workers.dev"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Confirm your email - RaidSync"
content_path = "./supabase/templates/confirmation.html"
